(function () {
  'use strict';

  function initDisclaimer() {
    if (localStorage.getItem("medicalDisclaimerAccepted") === "true") {
      return;
    }

    if (document.getElementById('medical-ai-disclaimer-overlay')) {
      return;
    }

    var style = document.createElement('style');
    style.id = 'medical-ai-disclaimer-styles';
    style.textContent = `
      #medical-ai-disclaimer-overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100vw;
        height: 100vh;
        background: rgba(10, 15, 30, 0.88);
        backdrop-filter: blur(14px);
        -webkit-backdrop-filter: blur(14px);
        z-index: 999999;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 20px;
        box-sizing: border-box;
        opacity: 0;
        transition: opacity 0.3s ease;
      }
      #medical-ai-disclaimer-overlay.visible {
        opacity: 1;
      }
      #medical-ai-disclaimer-card {
        background: linear-gradient(145deg, rgba(15, 23, 42, 0.98), rgba(26, 36, 60, 0.98));
        border: 1px solid rgba(0, 212, 255, 0.3);
        border-radius: 20px;
        max-width: 520px;
        width: 100%;
        padding: 28px 24px;
        box-shadow: 0 25px 60px rgba(0, 0, 0, 0.8), 0 0 30px rgba(0, 212, 255, 0.15);
        color: #f8fafc;
        font-family: 'Outfit', 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
        transform: translateY(20px);
        transition: transform 0.3s ease;
        box-sizing: border-box;
      }
      #medical-ai-disclaimer-overlay.visible #medical-ai-disclaimer-card {
        transform: translateY(0);
      }
      .disclaimer-header {
        display: flex;
        align-items: center;
        gap: 12px;
        margin-bottom: 18px;
        padding-bottom: 14px;
        border-bottom: 1px solid rgba(255, 255, 255, 0.12);
      }
      .disclaimer-header h2 {
        font-size: 1.35rem;
        font-weight: 700;
        color: #ffffff;
        margin: 0;
        display: flex;
        align-items: center;
        gap: 8px;
      }
      .disclaimer-body {
        font-size: 0.92rem;
        line-height: 1.6;
        color: rgba(241, 245, 249, 0.9);
        margin-bottom: 24px;
      }
      .disclaimer-body p {
        margin: 0 0 12px 0;
      }
      .disclaimer-body p:last-child {
        margin-bottom: 0;
      }
      .disclaimer-warning-box {
        background: rgba(239, 68, 68, 0.12);
        border-left: 4px solid #ef4444;
        padding: 12px 14px;
        border-radius: 8px;
        margin-top: 14px;
        color: #fca5a5;
        font-size: 0.88rem;
        font-weight: 500;
      }
      .disclaimer-footer {
        display: flex;
        justify-content: flex-end;
      }
      .disclaimer-btn {
        width: 100%;
        padding: 14px 24px;
        background: linear-gradient(90deg, #00D4FF, #7C3AED);
        color: #ffffff;
        font-weight: 700;
        font-size: 1rem;
        border: none;
        border-radius: 12px;
        cursor: pointer;
        transition: all 0.25s ease;
        box-shadow: 0 8px 20px -4px rgba(0, 212, 255, 0.4);
        text-align: center;
      }
      .disclaimer-btn:hover {
        transform: translateY(-2px);
        box-shadow: 0 12px 25px -4px rgba(0, 212, 255, 0.6);
      }
      .disclaimer-btn:active {
        transform: translateY(0);
      }
    `;
    document.head.appendChild(style);

    var overlay = document.createElement('div');
    overlay.id = 'medical-ai-disclaimer-overlay';
    overlay.innerHTML = `
      <div id="medical-ai-disclaimer-card" role="dialog" aria-modal="true" aria-labelledby="disclaimer-title">
        <div class="disclaimer-header">
          <h2 id="disclaimer-title">⚠️ Medical AI Disclaimer</h2>
        </div>
        <div class="disclaimer-body">
          <p>HealLens AI provides preliminary health analysis for informational purposes only.</p>
          <p>The results generated by this application are based on Artificial Intelligence and must not be considered a medical diagnosis.</p>
          <p>HealLens does not replace qualified doctors, hospitals, laboratory tests, or professional medical advice.</p>
          <p>Always consult a licensed healthcare professional before making any medical decisions or starting any treatment.</p>
          <div class="disclaimer-warning-box">
            If you are experiencing severe symptoms or a medical emergency, seek immediate medical attention.
          </div>
        </div>
        <div class="disclaimer-footer">
          <button id="disclaimer-accept-btn" class="disclaimer-btn">I Understand</button>
        </div>
      </div>
    `;

    document.body.appendChild(overlay);

    requestAnimationFrame(function () {
      overlay.classList.add('visible');
    });

    var acceptBtn = document.getElementById('disclaimer-accept-btn');
    if (acceptBtn) {
      acceptBtn.addEventListener('click', function () {
        localStorage.setItem("medicalDisclaimerAccepted", "true");
        overlay.classList.remove('visible');
        setTimeout(function () {
          if (overlay.parentNode) {
            overlay.parentNode.removeChild(overlay);
          }
        }, 300);
      });
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initDisclaimer);
  } else {
    initDisclaimer();
  }
})();
